// Project + stack + content data, exported to window for app.jsx to consume.

const PROJECTS = [
  {
    id: "codevision",
    title: "CodeVision",
    subtitle: "Building-code agent for the web",
    category: "App Development",
    year: "2025",
    status: "In progress",
    href: "https://github.com/Userdflt",
    mark: "C",
    blurb: "Web app for real-time NZ Building Code assistance. Specialised AI agents, vector retrieval, deployed on Cloud Run.",
    tech: ["Next.js", "TypeScript", "FastAPI", "OpenAI Agents SDK", "Supabase", "pgvector", "Firebase"],
    details: {
      overview: "CodeVision is a production-grade web application that delivers real-time NZ Building Code guidance to designers, builders, and compliance staff. A team of specialised AI agents — each scoped to a section of the code — collaborate via the OpenAI Agents SDK to answer questions, surface citations, and flag ambiguity.",
      problem: "Building code is dense, fragmented, and slow to navigate. Practitioners lose hours flipping between PDFs, amendments, and acceptable solutions when they need a confident, sourced answer.",
      approach: [
        { t: "Agents over a single model", d: "Specialist agents for fire, structure, weathertightness, and accessibility — orchestrated via the OpenAI Agents SDK with a routing layer." },
        { t: "Sourced answers", d: "pgvector + Supabase auth backs every reply with citations to the exact clause." },
        { t: "Production-first", d: "Next.js + FastAPI deployed on Firebase Hosting and Google Cloud Run. Streaming responses, persistent sessions, evaluation hooks." },
      ],
      outcomes: ["Sub-2s first token over typical queries", "Citations on every clause-level answer", "Designed for compliance review traceability"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/code_vision.png", alt: "CodeVision overview" },
        { type: "video", src: "Videos/codeVision_test01.mp4", caption: "CodeVision walkthrough" },
      ],
    },
  },
  {
    id: "vision-studio",
    title: "Vision Studio",
    subtitle: "Multi-agent image generation",
    category: "Generative AI",
    year: "2025",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "V",
    blurb: "Turns short briefs into detailed prompts and professional visuals via Gemini. Specialised agents for inpainting, plans, and scene generation.",
    tech: ["React", "TypeScript", "Tailwind", "Gemini 2.5 Flash", "IndexedDB"],
    details: {
      overview: "Vision Studio is a multi-agent image-generation tool that converts a one-line brief into a structured prompt, then routes it to specialist agents — inpainting, floorplan layout, scene composition — powered by Google's Gemini 2.5 Flash.",
      problem: "Most image tools take raw prompts and deliver one-shot results. Architecture and design briefs need a structured pipeline — context, references, intent — before a useful image can be produced.",
      approach: [
        { t: "Brief → prompt agent", d: "Expands a sparse brief into a detailed, model-ready prompt with style, materials, lighting." },
        { t: "Specialist routing", d: "Different agents handle inpainting, plan generation, and free-form scenes." },
        { t: "Local persistence", d: "IndexedDB stores sessions, references, and history without a backend." },
      ],
      outcomes: ["100% client-side; deployable as a static site", "Mid-brief refinement loops without re-prompting"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/Vision Studio logo.png", alt: "Vision Studio" },
      ],
    },
  },
  {
    id: "n8n-rag",
    title: "n8n Building Code RAG",
    subtitle: "Multi-agent retrieval system",
    category: "Multi-agent RAG",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "n",
    blurb: "Sophisticated multi-agent RAG over NZ Building Code, built end-to-end in n8n. Specialist agents, OCR, intelligent query routing, Supabase vector store.",
    tech: ["n8n", "OpenAI GPT-4.1", "Mistral OCR", "Supabase", "Vector search"],
    details: {
      overview: "A full multi-agent RAG system over the NZ Building Code, built entirely in n8n. Mistral OCR converts source PDFs to clean text; embeddings land in Supabase pgvector; specialist agents answer scoped queries; a router decides who should respond.",
      problem: "Standard RAG over a long, structured code-document tends to hallucinate cross-references and miss section context. A single retriever can't tell fire from structure.",
      approach: [
        { t: "OCR → chunks → vectors", d: "Mistral OCR + heading-aware chunking → Supabase pgvector." },
        { t: "Router → specialist", d: "A lightweight router classifies the question, then a specialist agent answers with its scoped index." },
        { t: "Visual orchestration", d: "All wiring lives in n8n — easy to audit, fork, and extend with new specialists." },
      ],
      outcomes: ["End-to-end in n8n — no bespoke runtime to maintain", "Auditable flow per query"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/n8n.png", alt: "n8n RAG flow" },
        { type: "video", src: "Videos/YouCut_20250729_161540173.mp4", caption: "n8n RAG demo" },
      ],
    },
  },
  {
    id: "notion-mcp",
    title: "Notion MCP Agent",
    subtitle: "Live knowledge hub over Notion",
    category: "AI Agent",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "N",
    blurb: "FastMCP server exposing Notion as a toolbox. LangChain + GPT-4o orchestration for read, write, summarise, tables, metadata — even MP3s of notes.",
    tech: ["FastMCP", "Notion API", "LangChain", "LangGraph", "TTS"],
    details: {
      overview: "Notion MCP Agent turns a Notion workspace into a live, agent-driven knowledge hub. A FastMCP server exposes the Notion API as a toolbox; LangChain + GPT-4o orchestrate conversations to read, write, summarise, build tables, manage metadata, and produce MP3 audio of notes via TTS.",
      problem: "Notion is the centre of gravity for personal and team knowledge — but interacting with it through chat usually means dumb question-answering. The agent should be able to *do* things, not just describe them.",
      approach: [
        { t: "FastMCP as the tool layer", d: "Every Notion verb (create, append, query, schema) is a typed MCP tool." },
        { t: "LangChain + LangGraph orchestration", d: "GPT-4o reasons over the workspace and chains tool calls." },
        { t: "TTS output", d: "Spoken summaries of meeting notes, journals, and PRs as MP3." },
      ],
      outcomes: ["Conversational read/write over Notion", "Audio recap of long notes in seconds"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/mcp_logo.png", alt: "MCP logo" },
        { type: "gif", src: "gifs/Table_Creation.gif", alt: "Table creation in Notion via MCP", caption: "Table creation" },
        { type: "gif", src: "gifs/writing_structured_notes.gif", alt: "Writing structured notes", caption: "Structured note authoring" },
      ],
    },
  },
  {
    id: "stable-diffusion",
    title: "GenAI Sketch → Image",
    subtitle: "Stable Diffusion XL + ControlNet",
    category: "Generative AI",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "S",
    blurb: "Interactive sketch-to-image tool with ControlNet conditioning for precise architectural exploration.",
    tech: ["Diffusers", "SDXL", "ControlNet", "PyTorch", "Tkinter"],
    details: {
      overview: "An interactive sketch-to-image tool that pairs Stable Diffusion XL with ControlNet conditioning so freehand line drawings drive precise, architectural-grade generations. Built as a desktop tool with Tkinter, backed by the Hugging Face Diffusers pipeline.",
      problem: "Pure text-to-image is too unconstrained for early architectural exploration. You need the image to follow a specific massing, line, or plan — without losing the freedom of generative.",
      approach: [
        { t: "ControlNet for structure", d: "Edge / scribble conditioning lets the generation follow the sketch." },
        { t: "SDXL for fidelity", d: "Higher-resolution base for materials and lighting." },
        { t: "Native UI", d: "Tkinter app keeps the loop fast: sketch → generate → refine." },
      ],
      outcomes: ["Real-time iteration on architectural concepts", "Repeatable style and structure across variations"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/stable_sketch.png", alt: "Sketch input" },
        { type: "gif", src: "gifs/sd1.gif", alt: "Stable Diffusion run 1" },
        { type: "gif", src: "gifs/sd2.gif", alt: "Stable Diffusion run 2" },
        { type: "gallery", title: "Outputs", items: [
          { src: "images/3.jpeg", alt: "Output 3" },
          { src: "images/6.jpeg", alt: "Output 6" },
          { src: "images/image5.png", alt: "Output 5" },
          { src: "images/output2.png", alt: "Output 2" },
          { src: "images/image.3.png", alt: "Output 3 variant" },
        ]},
      ],
    },
  },
  {
    id: "vision-rag",
    title: "Vision Model RAG",
    subtitle: "ViT + RAG over building code PDFs",
    category: "ViT & RAG",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "V",
    blurb: "Extracts, indexes, and retrieves text and visual data from NZ Building Code PDFs with open-source vision models.",
    tech: ["LangChain", "LangGraph", "Ollama", "ChromaDB", "Streamlit"],
    details: {
      overview: "Vision Model RAG indexes both the text and figures of the NZ Building Code. A vision-language model captions diagrams and tables; the captions plus original chunks are embedded into ChromaDB; LangGraph orchestrates a retrieval graph; a Streamlit UI exposes it.",
      problem: "Standard text RAG drops the diagrams. For a code document, the diagram often *is* the answer.",
      approach: [
        { t: "Vision-language captioning", d: "LLaMA Vision via Ollama captions every figure on extraction." },
        { t: "Multi-modal index", d: "Captions + text chunks share an embedding space in ChromaDB." },
        { t: "Graph retrieval", d: "LangGraph composes the retrieve → answer → verify path." },
      ],
      outcomes: ["Figures retrievable by semantic question", "Open-source end-to-end — fully local"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/codevision.png", alt: "Vision Model RAG cover" },
        { type: "image", src: "images/Workflow_Diagram.jpeg", alt: "Workflow diagram", caption: "Retrieval workflow" },
        { type: "image", src: "images/Sample_extracted.png", alt: "Sample extracted figure", caption: "Extracted figure sample" },
      ],
    },
  },
  {
    id: "llm-rag",
    title: "Self-correcting RAG",
    subtitle: "Autonomous decision graph",
    category: "Advanced RAG",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "L",
    blurb: "Self-correcting retrieval with autonomous decision-making for more accurate, reliable answers under ambiguity.",
    tech: ["LangChain", "LangGraph", "ChromaDB", "Ollama"],
    details: {
      overview: "A self-correcting RAG system that grades its own retrievals, rewrites failing queries, and decides autonomously when to fall back to web search or refuse. Built on LangGraph as a state machine; Ollama runs models locally.",
      problem: "Naive RAG returns whatever it retrieves, even when the retrieval is bad. The system should know when it doesn't know.",
      approach: [
        { t: "Grade the retrieval", d: "A grader LLM evaluates whether retrieved chunks actually answer the query." },
        { t: "Rewrite & retry", d: "Failing queries are rewritten; the graph loops until a confident answer or a bounded refusal." },
        { t: "Local-first", d: "Ollama keeps everything on-device for privacy." },
      ],
      outcomes: ["Higher answer precision on ambiguous queries", "Graceful refusal instead of hallucination"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/LLM.png", alt: "LLM RAG system" },
        { type: "image", src: "images/llm_flow_chart_1.jpeg", alt: "LLM RAG flow chart 1", caption: "Decision graph" },
        { type: "image", src: "images/llm_flow_chart_2.jpeg", alt: "LLM RAG flow chart 2", caption: "Self-correction loop" },
      ],
    },
  },
  {
    id: "cv-safety",
    title: "Construction Safety CV",
    subtitle: "YOLOv9 hazard detection",
    category: "Computer Vision",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "Y",
    blurb: "Real-time object detection for PPE compliance and hazard prevention on construction sites.",
    tech: ["YOLOv9", "OpenCV", "PyTorch", "Pandas"],
    details: {
      overview: "A real-time computer-vision system that detects PPE compliance (helmet, vest, harness) and common site hazards across construction-site footage. Trained on a curated dataset using YOLOv9; deployable to edge devices via ONNX export.",
      problem: "Site safety reviews happen after incidents, not before. Real-time detection turns the camera into a passive supervisor that flags non-compliance instantly.",
      approach: [
        { t: "Curated dataset", d: "Pulled from public site footage and labelled in batches." },
        { t: "YOLOv9 + ByteTrack", d: "Fast inference with cross-frame tracking for stable IDs." },
        { t: "ONNX export", d: "Deployable to edge devices for on-site processing." },
      ],
      outcomes: ["Sub-frame inference on commodity GPUs", "Edge-deployable via ONNX"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/output8.png", alt: "CV detection output 8" },
        { type: "image", src: "images/output1.png", alt: "CV detection output 1" },
        { type: "gif", src: "gifs/construction_workers.gif", alt: "Construction workers PPE detection", caption: "Live PPE detection" },
      ],
    },
  },
  {
    id: "youtube-analytics",
    title: "YouTube Analytics",
    subtitle: "Statistical study of AI content trends",
    category: "Data Science",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "Y",
    blurb: "EDA + hypothesis testing on YouTube AI/data-science content. Temporal patterns, engagement, ANOVA across cohorts.",
    tech: ["Python", "YouTube API", "Pandas", "ANOVA"],
    details: {
      overview: "A statistical study of AI / data-science content on YouTube. Data collected via the YouTube API, cleaned, explored, and tested for temporal patterns and engagement shifts across cohorts using ANOVA and follow-up post-hoc tests.",
      problem: "Anecdotal evidence suggested the AI content boom changed the shape of educational YouTube — but by how much, and across which dimensions? A rigorous study, not vibes.",
      approach: [
        { t: "API ingestion + cleaning", d: "Collected channel and video metadata; normalised across time and category." },
        { t: "EDA → hypotheses", d: "Visualised temporal patterns; formed testable hypotheses about engagement shifts." },
        { t: "ANOVA + post-hoc", d: "Tested cohort differences; reported effect sizes alongside p-values." },
      ],
      outcomes: ["Statistically significant cohort effects on engagement", "Reproducible notebook"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/youtube_analytics.png", alt: "YouTube Analytics dashboard" },
      ],
    },
  },
  {
    id: "nasa-outgassing",
    title: "NASA Outgassing",
    subtitle: "ML for space-grade materials",
    category: "Data Science",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "◊",
    blurb: "Predictive models on TML, CVCM, WVR metrics for space-grade material evaluation and QC.",
    tech: ["scikit-learn", "Regression", "Classification", "Feature eng."],
    details: {
      overview: "Machine-learning models for NASA outgassing metrics — TML (Total Mass Loss), CVCM (Collected Volatile Condensable Materials), and WVR (Water Vapour Regained). The goal: predict whether a material will pass space-grade thresholds before physical testing.",
      problem: "Outgassing tests are expensive and slow. A reliable predictive model accelerates material selection for satellites and spacecraft.",
      approach: [
        { t: "Feature engineering", d: "Engineered chemical / physical descriptors from raw material data." },
        { t: "Regression + classification", d: "Regression on the three metrics; classification on pass/fail thresholds." },
        { t: "Cross-validated reporting", d: "Reported error bars and confusion matrices honestly." },
      ],
      outcomes: ["Pass/fail prediction with reportable confidence", "Honest error analysis"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/nasa_outgassing.png", alt: "NASA Outgassing analysis" },
      ],
    },
  },
  {
    id: "ai-detection",
    title: "AI Content Detection",
    subtitle: "Human vs. AI news classifier",
    category: "NLP",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "A",
    blurb: "NLP system distinguishing human-written vs AI-generated news using stylometric features and DL models.",
    tech: ["NLTK", "spaCy", "Deep learning"],
    details: {
      overview: "An NLP classifier for distinguishing human-written from AI-generated news articles. Combines classical stylometric features (sentence length, lexical diversity, punctuation rhythm) with deep-learning text embeddings.",
      problem: "Detecting AI-generated content is a moving target, but the right ensemble of stylistic features still beats either approach alone in many domains.",
      approach: [
        { t: "Stylometric features", d: "Sentence length, lexical diversity, punctuation rhythm via NLTK / spaCy." },
        { t: "Embedding features", d: "Transformer embeddings as a second feature stream." },
        { t: "Ensemble", d: "Combined classifier balances explainability and accuracy." },
      ],
      outcomes: ["Strong baseline on news-domain data", "Explainable feature importance"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/ai_detection.png", alt: "AI content detection" },
      ],
    },
  },
  {
    id: "wind-energy",
    title: "Wind Energy Prediction",
    subtitle: "Forecasting turbine output",
    category: "Data Science",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "W",
    blurb: "Predicting wind-turbine power output from weather data with regression and neural models for renewable optimisation.",
    tech: ["Time series", "XGBoost", "Neural nets"],
    details: {
      overview: "Predicting wind-turbine power output from weather data — wind speed and direction, temperature, pressure — with a stack of regression, gradient-boosted, and neural models. Used as a teaching project for time-series forecasting fundamentals.",
      problem: "Turbine output is highly variable. Better short-horizon forecasts mean better grid balancing and revenue forecasting.",
      approach: [
        { t: "Feature engineering", d: "Lagged windows, rolling stats, weather derivatives." },
        { t: "Model stack", d: "Linear baselines, XGBoost, and a small neural net compared head-to-head." },
        { t: "Honest evaluation", d: "Time-aware CV (no leakage); reported MAE / RMSE per horizon." },
      ],
      outcomes: ["XGBoost outperformed neural baseline on short horizons", "Reproducible eval pipeline"],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "image", src: "images/wind_energy.png", alt: "Wind energy prediction" },
      ],
    },
  },
  {
    id: "ai-visualizations",
    title: "AI Architectural Visualizations",
    subtitle: "Generative visualization for architecture",
    category: "Generative AI",
    year: "2024",
    status: "Live",
    href: "https://github.com/Userdflt",
    mark: "◇",
    blurb: "Exploring the intersection of AI and architectural design through generative visualization — text-to-render, model-to-render, sketch-to-render, plans, masterplans, and AI-generated walkthrough videos.",
    tech: ["ComfyUI", "Stable Diffusion", "ControlNet", "Sketch-to-render", "AI video"],
    details: {
      overview: "Exploring the intersection of artificial intelligence and architectural design through generative visualization techniques.",
      approach: [
        { t: "Text → render", d: "Conceptual scenes from prompts: residential village, cafes, entries, interiors." },
        { t: "Sketch → render", d: "Freehand sketches conditioned through ControlNet to produce coherent architectural variations." },
        { t: "Model → render", d: "Massing and model exports re-rendered into day and night photoreal scenes." },
        { t: "Plan → render", d: "Floor plans expanded into rendered interiors and elevations." },
        { t: "AI video", d: "Cabin construction, shopping mall, residential village, and morning residence walkthroughs." },
      ],
      links: [{ label: "GitHub profile", href: "https://github.com/Userdflt" }],
      media: [
        { type: "gallery", title: "Featured ComfyUI Workflow", items: [
          { src: "images/ai_visual_images/text_to_render/final_w_ppl.png", alt: "Residential Village Overview", caption: "Residential Village Overview" },
          { src: "images/ai_visual_images/text_to_render/entry_w_ppl.png", alt: "Residential Village Entry", caption: "Residential Village Entry" },
          { src: "images/ai_visual_images/text_to_render/cafe_w_ppl.png", alt: "Residential Village Cafe", caption: "Residential Village Cafe" },
          { src: "images/ai_visual_images/text_to_render/residentail_units_w_ppl.png", alt: "Residential Units with People", caption: "Residential Units" },
          { src: "images/ai_visual_images/ComfyUI_workflow/Cabin_render_highq.jpg", alt: "Cabin High Quality Render", caption: "Cabin High Quality Render" },
          { src: "images/ai_visual_images/model_to_render/AI_interior_render_1.jpg", alt: "AI Interior Render 1", caption: "AI Interior Render 1" },
          { src: "images/ai_visual_images/model_to_render/AI_interior_render_2.jpg", alt: "AI Interior Render 2", caption: "AI Interior Render 2" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00013_.png", alt: "ComfyUI Workflow Output 1", caption: "ComfyUI Workflow Output 1" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00014_.png", alt: "ComfyUI Workflow Output 2", caption: "ComfyUI Workflow Output 2" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00018_.png", alt: "ComfyUI Workflow Output 3", caption: "ComfyUI Workflow Output 3" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00022_.png", alt: "ComfyUI Workflow Output 4", caption: "ComfyUI Workflow Output 4" },
        ]},
        { type: "video", src: "Videos/cabin_construction.mp4", caption: "Cabin Construction Process" },
        { type: "video", src: "Videos/shopping_mall.mp4", caption: "Shopping Mall Visualization" },
        { type: "video", src: "Videos/resi_village_v2.mp4", caption: "Residential Village" },
        { type: "video", src: "Videos/morning architecture.mp4", caption: "Morning Residence" },
        { type: "gallery", title: "More AI Visualizations", items: [
          { src: "images/ai_visual_images/text_to_render/final_w_ppl.png", alt: "Residential Village Overview", caption: "Residential Village Overview" },
          { src: "images/ai_visual_images/text_to_render/cafe_w_ppl.png", alt: "Residential Village Cafe", caption: "Residential Village Cafe" },
          { src: "images/ai_visual_images/text_to_render/entry_w_ppl.png", alt: "Residential Village Entry", caption: "Residential Village Entry" },
          { src: "images/ai_visual_images/text_to_render/residentail_units_w_ppl.png", alt: "Residential Units", caption: "Residential Units" },
          { src: "images/ai_visual_images/ComfyUI_workflow/Cabin_sample_model.png", alt: "Cabin Sample Model", caption: "Cabin Sample Model" },
          { src: "images/ai_visual_images/ComfyUI_workflow/Cabin_render_highq.jpg", alt: "Cabin High Quality Render", caption: "Cabin High Quality Render" },
          { src: "images/ai_visual_images/model_to_render/interior_render_1.png", alt: "Interior Render 1", caption: "Interior Render 1" },
          { src: "images/ai_visual_images/model_to_render/AI_interior_render_1.jpg", alt: "AI Interior Render 1", caption: "AI Interior Render 1" },
          { src: "images/ai_visual_images/model_to_render/interior_render_2.png", alt: "Interior Render 2", caption: "Interior Render 2" },
          { src: "images/ai_visual_images/model_to_render/AI_interior_render_2.jpg", alt: "AI Interior Render 2", caption: "AI Interior Render 2" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00013_.png", alt: "ComfyUI Workflow Output 1", caption: "ComfyUI Workflow Output 1" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00014_.png", alt: "ComfyUI Workflow Output 2", caption: "ComfyUI Workflow Output 2" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00018_.png", alt: "ComfyUI Workflow Output 3", caption: "ComfyUI Workflow Output 3" },
          { src: "images/ai_visual_images/ComfyUI_workflow/ComfyUI_00022_.png", alt: "ComfyUI Workflow Output 4", caption: "ComfyUI Workflow Output 4" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_4/20220705_175328.jpg", alt: "Sketch 4 Original", caption: "Sketch 4 — Original" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_4/2025-11-09_10-23.png", alt: "Sketch 4 Render 1", caption: "Sketch 4 — Render 1" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_1/sketch_1.jpg", alt: "Sketch 1 Original", caption: "Sketch 1 — Original" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_1/sketch_1_render_2.png", alt: "Sketch 1 Render 2", caption: "Sketch 1 — Render 2" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_1/sketch_1_render_3.png", alt: "Sketch 1 Render 3", caption: "Sketch 1 — Render 3" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_1/sketch_1_render_4.png", alt: "Sketch 1 Render 4", caption: "Sketch 1 — Render 4" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_1/sketch_1_render_5.png", alt: "Sketch 1 Render 5", caption: "Sketch 1 — Render 5" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_2/nano-banana-image-1 (3).png", alt: "Sketch 2 Render 1", caption: "Sketch 2 — Render 1" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_2/nano-banana-image-22.png", alt: "Sketch 2 Render 2", caption: "Sketch 2 — Render 2" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_3/sketch_3.jpg", alt: "Sketch 3 Original", caption: "Sketch 3 — Original" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_3/sketch_3_render_1.png", alt: "Sketch 3 Render 1", caption: "Sketch 3 — Render 1" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_3/sketch_3_render_2.png", alt: "Sketch 3 Render 2", caption: "Sketch 3 — Render 2" },
          { src: "images/ai_visual_images/sketch_to_render/sketch_3/sketch_3_render_3.png", alt: "Sketch 3 Render 3", caption: "Sketch 3 — Render 3" },
          { src: "images/ai_visual_images/model_to_render/model_1.png", alt: "Model 1 Original", caption: "Model 1 — Original" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_1.png", alt: "Model 1 Render 1", caption: "Model 1 — Render 1" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_1_night.png", alt: "Model 1 Render 1 Night", caption: "Model 1 — Render 1 Night" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_2.png", alt: "Model 1 Render 2", caption: "Model 1 — Render 2" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_2_night.png", alt: "Model 1 Render 2 Night", caption: "Model 1 — Render 2 Night" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_3.png", alt: "Model 1 Render 3", caption: "Model 1 — Render 3" },
          { src: "images/ai_visual_images/model_to_render/model_1_render_3_night.png", alt: "Model 1 Render 3 Night", caption: "Model 1 — Render 3 Night" },
          { src: "images/ai_visual_images/plan_to_render/plan_1.png", alt: "Plan 1 Original", caption: "Plan 1 — Original" },
          { src: "images/ai_visual_images/plan_to_render/plan_1_render_1.png", alt: "Plan 1 Render 1", caption: "Plan 1 — Render 1" },
          { src: "images/ai_visual_images/plan_to_render/plan_1_render_2.png", alt: "Plan 1 Render 2", caption: "Plan 1 — Render 2" },
          { src: "images/ai_visual_images/plan_to_render/plan_2.png", alt: "Plan 2 Original", caption: "Plan 2 — Original" },
          { src: "images/ai_visual_images/plan_to_render/plan_2_render_1.png", alt: "Plan 2 Render 1", caption: "Plan 2 — Render 1" },
          { src: "images/ai_visual_images/plan_to_render/plan_2_render_2.png", alt: "Plan 2 Render 2", caption: "Plan 2 — Render 2" },
          { src: "images/ai_visual_images/plan_to_render/plan_3.png", alt: "Plan 3 Original", caption: "Plan 3 — Original" },
          { src: "images/ai_visual_images/plan_to_render/plan_3_render_1.png", alt: "Plan 3 Render 1", caption: "Plan 3 — Render 1" },
          { src: "images/ai_visual_images/plan_to_render/plan_3_render_2.png", alt: "Plan 3 Render 2", caption: "Plan 3 — Render 2" },
          { src: "images/ai_visual_images/text_to_render/render_1.png", alt: "Text to Render 1", caption: "Text to Render 1" },
          { src: "images/ai_visual_images/text_to_render/render_2.png", alt: "Text to Render 2", caption: "Text to Render 2" },
          { src: "images/ai_visual_images/text_to_render/interior_render_1.png", alt: "Interior Render 1", caption: "Interior Render 1" },
          { src: "images/ai_visual_images/text_to_render/interior_render_2.png", alt: "Interior Render 2", caption: "Interior Render 2" },
          { src: "images/ai_visual_images/masterplan_render/masterplan_1.png", alt: "Masterplan 1 Original", caption: "Masterplan 1 — Original" },
          { src: "images/ai_visual_images/masterplan_render/masterplan_1_render_1.png", alt: "Masterplan 1 Render 1", caption: "Masterplan 1 — Render 1" },
          { src: "images/ai_visual_images/masterplan_render/masterplan_1_render_2.png", alt: "Masterplan 1 Render 2", caption: "Masterplan 1 — Render 2" },
          { src: "images/ai_visual_images/masterplan_render/masterplan_1_render_4.png", alt: "Masterplan 1 Render 4", caption: "Masterplan 1 — Render 4" },
          { src: "images/ai_visual_images/bg_add_render/bg.png", alt: "Background Original", caption: "Background Original" },
          { src: "images/ai_visual_images/bg_add_render/first_concept.png", alt: "First Concept", caption: "First Concept" },
          { src: "images/ai_visual_images/bg_add_render/first_concept_w_ppl.png", alt: "First Concept with People", caption: "First Concept with People" },
          { src: "images/ai_visual_images/bg_add_render/first_concept_modified.png", alt: "First Concept Modified", caption: "First Concept Modified" },
          { src: "images/ai_visual_images/bg_add_render/concept_1.png", alt: "Concept 1", caption: "Concept 1" },
          { src: "images/ai_visual_images/bg_add_render/concept_2.png", alt: "Concept 2", caption: "Concept 2" },
          { src: "images/ai_visual_images/bg_add_render/concept_2_w_ppl.png", alt: "Concept 2 with People", caption: "Concept 2 with People" },
        ]},
      ],
    },
  },
];

const STACK = [
  {
    head: "01 / Languages & Frameworks",
    title: "Build & ship",
    tags: ["Python", "TypeScript", "Next.js", "FastAPI", "PyTorch", "Keras", "Streamlit"],
  },
  {
    head: "02 / Agents & RAG",
    title: "Orchestration",
    tags: ["LangChain", "LangGraph", "OpenAI Agents SDK", "FastMCP", "n8n", "Multi-agent"],
  },
  {
    head: "03 / Generative & Vision",
    title: "Models & vision",
    tags: ["Stable Diffusion XL", "ControlNet", "YOLOv9", "Mistral OCR", "Hugging Face", "OpenCV"],
  },
  {
    head: "04 / Governance & Adoption",
    title: "Make it safe to scale",
    tags: ["Risk tiering", "Evals", "Privacy controls", "Playbooks", "Prompt standards", "Feedback loops"],
  },
];

const PRINCIPLES = [
  { n: "01", t: "Build for adoption", d: "Tools only matter if teams use them. I design with playbooks, prompt standards, and feedback loops baked in." },
  { n: "02", t: "Reliability over novelty", d: "Risk tiering, data and privacy controls, evaluation standards, audit-friendly processes — built in from day one." },
  { n: "03", t: "Architectural thinking", d: "Seven years in architecture practice taught me to move from messy constraints to clear, testable systems." },
  { n: "04", t: "Measure what matters", d: "Quality, time saved, adoption, risk reduction — define metrics, then iterate on what they tell you." },
];

Object.assign(window, { PROJECTS, STACK, PRINCIPLES });
