import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch();
const base='http://localhost:4173/';
const projects=JSON.parse(fs.readFileSync('content/projects.json','utf8'));
const pages=['index.html','projects.html','about.html','contact.html',...projects.map(p=>`projects/${p.slug}.html`),'project.html','404.html','test-performance.html'];
const errors=[];const findings=[];
fs.mkdirSync('.preview',{recursive:true});
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))errors.push(`${r.status()} ${r.url()}`);});
 for(const file of pages){
  await page.goto(base+file);
  await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=900){scrollTo(0,y);await new Promise(r=>setTimeout(r,25));}scrollTo(0,0);});
  await page.waitForFunction(()=>[...document.images].filter(i=>!i.closest('dialog')&&!i.closest('details:not([open])')).every(i=>i.complete));
  const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.src&&!i.closest('dialog')&&!i.closest('details:not([open])')&&i.complete&&!i.naturalWidth).map(i=>i.src));
  assert.deepEqual(broken,[],file+' images');
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  const violations=axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));
  if(violations.length)findings.push({file,violations});
  for(const width of [1440,768,390,320]){
   await page.setViewportSize({width,height:1000});
   await page.waitForTimeout(100);
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${file}: overflow at ${width}`);
  }
  await page.setViewportSize({width:1440,height:1000});
  if(['index.html','about.html','contact.html','projects.html','projects/n8n_rag.html','projects/ai-visualizations.html'].includes(file))await page.screenshot({path:'.preview/'+file.replaceAll('/','-')+'.png',fullPage:true});
  console.log(`Audited ${file}`);
 }
 await page.goto(base+'projects.html');
 await page.getByRole('button',{name:'Data science 4',exact:true}).click();
 assert.equal(await page.locator('.project-grid .project-card:visible').count(),4);
 assert.ok(page.url().includes('category=Data+science'));
 await page.locator('#project-search').fill('wind');
 await page.waitForFunction(()=>document.querySelector('#project-count').textContent.startsWith('1 project'));
 assert.equal(await page.locator('.project-grid .project-card:visible').count(),1);
 await page.reload();
 assert.equal(await page.locator('.project-grid .project-card:visible').count(),1);
 await page.locator('#project-search').fill('no-matching-project');
 await page.getByRole('button',{name:'Clear filters'}).waitFor({state:'visible'});
 await page.getByRole('button',{name:'Clear filters'}).click();
 assert.equal(await page.locator('.project-grid .project-card:visible').count(),13);
 await page.getByRole('button',{name:'Generative AI 3',exact:true}).click();
 await page.goBack();
 assert.equal(await page.locator('.project-grid .project-card:visible').count(),13);
 await page.goto(base+'projects/stablediffusion.html');
 const gallery=page.locator('#project-gallery [data-gallery]').first();
 const galleryCount=projects.find(project=>project.id==='stable-diffusion').gallery.length;
 await gallery.click();await page.locator('dialog[open]').waitFor();
 assert.equal(await page.locator('.lightbox-counter').innerText(),`1 / ${galleryCount}`);
 await page.keyboard.press('ArrowRight');assert.equal(await page.locator('.lightbox-counter').innerText(),`2 / ${galleryCount}`);
 await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 assert.ok(await gallery.evaluate(e=>document.activeElement===e));
 await page.goto(base+'projects/notion_mcp.html');
 await page.locator('[data-gif]').first().click();
 assert.ok((await page.locator('[data-gif] img').first().getAttribute('src')).endsWith('.gif'));
 await page.locator('[data-gif]').first().click();
 assert.ok((await page.locator('[data-gif] img').first().getAttribute('src')).endsWith('.webp'));
 await page.goto(base+'project.html?id=vision-rag');await page.waitForURL('**/projects/vision_model.html');
 await page.goto(base+'projects/n8n_rag.html');
 await page.locator('video').evaluate(video=>{video.muted=true;return video.play();});
 await page.waitForFunction(()=>document.querySelector('video').currentTime>0);
 await page.locator('video').evaluate(video=>video.pause());
 await page.setViewportSize({width:390,height:844});await page.goto(base+'index.html');
 await page.getByRole('button',{name:'Open navigation',exact:true}).click();
 await page.getByRole('navigation').getByRole('link',{name:'Projects',exact:true}).click();
 await page.waitForURL('**/projects.html');
 await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.keyboard.press('Escape');
 assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');
 const mobileAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 if(mobileAxe.violations.length)findings.push({file:'mobile projects',violations:mobileAxe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});
 await context.close();
 const plain=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const plainPage=await plain.newPage();
 await plainPage.goto(base);
 assert.ok(await plainPage.locator('.tablet-actions a').first().isVisible());
 assert.equal(await plainPage.locator('.hero-tablet').evaluate(e=>getComputedStyle(e).transform),'none');
 await plainPage.goto(base+'projects.html');assert.equal(await plainPage.locator('.project-card').count(),13);
 assert.ok(await plainPage.getByRole('navigation').getByRole('link',{name:'Projects',exact:true}).isVisible());
 await plain.close();
 const animated=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
 const animatedPage=await animated.newPage();animatedPage.on('pageerror',e=>errors.push(e.message));
 await animatedPage.goto(base);
 await animatedPage.waitForFunction(()=>document.querySelector('[data-tablet-hero]').dataset.heroState==='revealing');
 // Tabbing into the emerging screen must reveal the focused link immediately.
 await animatedPage.locator('.tablet-actions a').first().focus();
 assert.equal(await animatedPage.locator('[data-tablet-hero]').getAttribute('data-hero-state'),'ready');
 assert.equal(await animatedPage.locator('.tablet-actions').evaluate(e=>getComputedStyle(e).opacity),'1');
 await animatedPage.reload();
 await animatedPage.waitForFunction(()=>document.querySelector('[data-tablet-hero]').dataset.heroState==='ready');
 const settledTablet=await animatedPage.locator('.hero-tablet').boundingBox();
 await animatedPage.waitForTimeout(150);
 assert.deepEqual(await animatedPage.locator('.hero-tablet').boundingBox(),settledTablet);
 await animatedPage.reload();
 await animatedPage.waitForFunction(()=>document.querySelector('[data-tablet-hero]').dataset.heroState==='revealing');
 await animatedPage.emulateMedia({reducedMotion:'reduce'});
 await animatedPage.waitForFunction(()=>getComputedStyle(document.querySelector('.hero-tablet')).transform==='none');
 assert.equal(await animatedPage.locator('.tablet-actions').evaluate(e=>getComputedStyle(e).opacity),'1');
 await animatedPage.emulateMedia({reducedMotion:'no-preference'});
 await animatedPage.waitForFunction(()=>!document.documentElement.classList.contains('motion-paused'));
 assert.equal(await animatedPage.locator('.motion-toggle').textContent(),'Motion: on');
 await animatedPage.getByRole('button',{name:'Motion: on — turn animations off'}).click();
 assert.ok(await animatedPage.locator('html').evaluate(e=>e.classList.contains('motion-paused')));
 await animatedPage.reload();assert.equal(await animatedPage.locator('.motion-toggle').textContent(),'Motion: off');
 await animated.close();
 const unavailableMotion=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'no-preference'});
 const fallbackPage=await unavailableMotion.newPage();
 await fallbackPage.route('**/vendor/anime.esm.min.js',route=>route.abort());
 await fallbackPage.goto(base);
 await fallbackPage.waitForFunction(()=>document.documentElement.classList.contains('motion-paused'));
 assert.ok(await fallbackPage.locator('.tablet-actions a').first().isVisible());
 assert.equal(await fallbackPage.locator('.hero-tablet').evaluate(e=>getComputedStyle(e).transform),'none');
 await unavailableMotion.close();
 fs.writeFileSync('.preview/accessibility.json',JSON.stringify(findings,null,2));
 console.log(JSON.stringify({findings,errors},null,2));
 assert.deepEqual(errors,[],'Browser errors');assert.deepEqual(findings,[],'Accessibility violations');
 console.log('Passed: 20 pages, four widths, accessibility, filters, URL history, gallery, videos, GIFs, mobile navigation, reduced motion, and no-JS fallback.');
} finally {await browser.close();}
